version: '3'

services:
  app:
    image: 'atom-id:latest'
    restart: always
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
#    depends_on:
#      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:mydb
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
#  flyway:
#    image: flyway/flyway
#    command: -url=jdbc:h2:mem:mydb -schemas=public -user=sa -password= migrate
#    volumes:
#      - ./migration:/flyway/sql
#    depends_on:
#      - db
#  db:
#    image: 'postgres:16'
#    container_name: db
#    environment:
#      - POSTGRES_USER=admin
#      - POSTGRES_PASSWORD=admin
#      - POSTGRES_DB=database
