version: '3'

services:
  app:
    image: 'atom-id:latest'
    restart: always
    build:
      context: .
    container_name: app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/database
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
  flyway:
    image: flyway/flyway
    command: -url=jdbc:postgresql://db:5432/database -schemas=public -user=admin -password=admin migrate
    volumes:
      - ./migration:/flyway/sql
    depends_on:
      - db
  db:
    image: 'postgres:16'
    container_name: db
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=database
